import type { Capability } from "./types";

export const CATALOG: Capability[] = [
  {
    id: "attention-bidding",
    name: "Attention-Based Bidding",
    description: "Bids weighted by attention metrics (Adelaide, Playground xyz) instead of viewability alone.",
    channels: ["display", "video"],
    kpis: ["VCR", "Viewability"],
    vendorTypes: ["SSP", "DSP"],
    limitations: "Premium inventory only; not supported on open-exchange.",
  },
  {
    id: "contextual-exclusion",
    name: "Contextual Exclusion Lists",
    description: "Pre-bid keyword and topic exclusion (UGC, news adjacencies, brand-unsafe contexts).",
    channels: ["display", "video"],
    kpis: ["VCR", "CTR", "Viewability"],
    vendorTypes: ["SSP", "DSP", "AdCP"],
    limitations: "Effectiveness varies by SSP taxonomy coverage.",
  },
  {
    id: "pubmatic-premium-video",
    name: "PubMatic Premium Video Deals",
    description: "Curated Canadian premium video deals via PubMatic SSP direct.",
    channels: ["video"],
    kpis: ["VCR", "Reach"],
    vendorTypes: ["SSP"],
    limitations: "Canadian inventory only.",
  },
  {
    id: "equativ-premium-video",
    name: "Equativ Premium Video Deals",
    description: "Equativ SSP direct deals on premium broadcaster inventory (Bell, Corus, Rogers).",
    channels: ["video"],
    kpis: ["VCR", "Reach"],
    vendorTypes: ["SSP"],
    limitations: "Inventory subject to publisher availability windows.",
  },
  {
    id: "magnite-ctv-deals",
    name: "Magnite CTV Deals",
    description: "Magnite SSP direct deals for CTV/OTT inventory across major Canadian streaming services.",
    channels: ["video", "ctv"],
    kpis: ["VCR", "Reach"],
    vendorTypes: ["SSP"],
    limitations: "CTV-only; not addressable for mobile/desktop video.",
  },
  {
    id: "adcp-publisher-direct",
    name: "AdCP Publisher-Direct Premium",
    description: "Direct buys against publisher inventory pools (Bell Media, Corus, Rogers Sports & Media).",
    channels: ["video", "display"],
    kpis: ["VCR", "Reach", "Viewability"],
    vendorTypes: ["AdCP"],
    limitations: "Manual deal activation required; not real-time.",
  },
  {
    id: "dv360-youtube",
    name: "DV360 YouTube Buying",
    description: "YouTube access via DV360 (TrueView, Bumper, Masthead).",
    channels: ["video", "youtube"],
    kpis: ["VCR", "Reach"],
    vendorTypes: ["DSP"],
    limitations: "Only path to YouTube inventory at scale; DSP gate requires YouTube in scope.",
  },
  {
    id: "ttd-retargeting",
    name: "TTD Retargeting",
    description: "Retargeting pools and 1P data activation via The Trade Desk.",
    channels: ["display", "video"],
    kpis: ["CTR", "CPA"],
    vendorTypes: ["DSP"],
    limitations: "Requires retargeting pool; not appropriate for prospecting-only briefs.",
  },
  {
    id: "amazon-dsp-retail",
    name: "Amazon DSP Retail Data",
    description: "Amazon DSP activation against retail shopper segments.",
    channels: ["display", "video"],
    kpis: ["CTR", "CPA"],
    vendorTypes: ["DSP"],
    limitations: "Strongest for endemic retail/CPG; weaker for awareness.",
  },
  {
    id: "audience-extension-ssp",
    name: "SSP Audience Extension",
    description: "Extend premium-deal audiences to look-alike inventory via SSP curation.",
    channels: ["display", "video"],
    kpis: ["Reach", "Viewability"],
    vendorTypes: ["SSP"],
    limitations: "Reach gains trade off against premium guarantee.",
  },
  {
    id: "frequency-cap-adserver",
    name: "Cross-Channel Frequency Cap (Ad Server)",
    description: "Unified frequency capping at the ad server across SSP, AdCP, and DSP lines.",
    channels: ["display", "video", "ctv", "youtube"],
    kpis: ["Reach", "VCR"],
    vendorTypes: ["SSP", "DSP", "AdCP"],
    limitations: "Requires consistent user ID resolution across vendors.",
  },
  {
    id: "brand-safety-prebid",
    name: "Pre-Bid Brand Safety (IAS/DV)",
    description: "Pre-bid filtering via IAS or DoubleVerify integrations on SSP and DSP paths.",
    channels: ["display", "video"],
    kpis: ["VCR", "Viewability"],
    vendorTypes: ["SSP", "DSP"],
    limitations: "Slight CPM premium; available on most major paths.",
  },
  {
    id: "video-completion-optimization",
    name: "Video Completion Optimization",
    description: "Bid shading and creative selection optimized against VCR delivery curves.",
    channels: ["video", "ctv"],
    kpis: ["VCR"],
    vendorTypes: ["SSP", "DSP"],
    limitations: "Requires 7+ days of campaign learning before optimization is meaningful.",
  },
  {
    id: "ix-private-deals",
    name: "Index Exchange Private Deals",
    description: "Index Exchange SSP curated deals for display and video.",
    channels: ["display", "video"],
    kpis: ["Viewability", "CTR"],
    vendorTypes: ["SSP"],
    limitations: "Stronger on display than video relative to PubMatic/Magnite.",
  },
  {
    id: "canadian-publisher-deals",
    name: "Canadian Publisher Direct Deals",
    description: "Direct deals with Canadian-owned publishers (Globe and Mail, La Presse, CBC).",
    channels: ["display", "video"],
    kpis: ["Reach", "Viewability"],
    vendorTypes: ["AdCP", "SSP"],
    limitations: "Inventory concentrated; reach ceiling per publisher.",
  },
];

export function getCapability(id: string): Capability | undefined {
  return CATALOG.find((c) => c.id === id);
}

export function capabilityIdsExist(ids: string[]): boolean {
  return ids.every((id) => CATALOG.some((c) => c.id === id));
}
